### ISSUE TITLE
Idea plugin doesn't compatible with IntelliJ IDEA 2021.3

### ISSUE THREAD

**Issue by kirimi** [Elementary-team/flutter-elementary#37]
Hello! 
Jetbrain's marketplace shows 'Not compatible with the version of your running IDE (IntelliJ IDEA 2021.3)'
Compatibility range  2020.3 — 2021.2.4

https://plugins.jetbrains.com/plugin/18099-elementary

**Comment by AlexeyBukin** [comment]
Thanks, we will try to fix it soon

**Comment by MbIXjkee** [comment]
@kirimi I have released intellij plugin version 0.0.2 with including this IDE's engine version. Try to check, please

**Comment by kirimi** [comment]
@MbIXjkee  It works now.  Thank you!
