### ISSUE TITLE
Proposal for the amendment of the documentation

### ISSUE THREAD

**Issue by GeorgeOblomov** [Elementary-team/flutter-elementary#52]
Hello!
Could you please add to docs the information that properties of the UI layer can be accessed inside the WidgetModel when called through the widget getter. I found it difficult to figure this out.  
Thanks in advance!

**Comment by MbIXjkee** [comment]
Hi! I think it is useful. Thanks for proposal, I'll do it.

**Comment by MbIXjkee** [comment]
Done
