### ISSUE TITLE
why screen referensed again in Country sample?

### ISSUE THREAD

**Issue by pishguy** [Elementary-team/flutter-elementary#79]
in `CountryListScreen` class we have `countryListScreenWidgetModelFactory` as a Factory

https://github.com/Elementary-team/flutter-elementary/blob/a61d1c86d380207d4d9533a1b790e70efab4c91a/examples/country/lib/ui/screen/country_list_screen/country_list_screen.dart#L10

and into that we have `CountryListScreenWidgetModel` class

https://github.com/Elementary-team/flutter-elementary/blob/a61d1c86d380207d4d9533a1b790e70efab4c91a/examples/country/lib/ui/screen/country_list_screen/country_list_screen_widget_model.dart#L16

and in this class `CountryListScreenWidgetModel` extends again screen as `CountryListScreen`

i can't understand why we should extend screen again

**Comment by MbIXjkee** [comment]
Hi! Thank you for your interest.
CountryListScreenWidgetModel doesn't extend CountryListScreen, it is parameterized by CountryListScreen. This is the approach's details https://dart.dev/language/generics. It is used here to make a link between types. For example
`class CountryListScreen extends ElementaryWidget<ICountryListWidgetModel> ` means the configuration of this view based on properties of the widget model with concrete implementation, described by ICountryListWidgetModel interface.
`class CountryListScreenWidgetModel extends WidgetModel<CountryListScreen, CountryListScreenModel> implements ICountryListWidgetModel` means that this widget model contains logic for CountryListScreen and uses a special type of model - CountryListScreenModel.

And regarding the factory, is an object with the responsibility of creating instances. It is not smth special, you can easily find this approach: the factory method. Here it helps to make the creation of the widget model more flexible and e.g substitute the widget model for tests.
