### ISSUE TITLE
using TickerProviderStateMixin

### ISSUE THREAD

**Issue by pishguy** [Elementary-team/flutter-elementary#80]
in MVVM model as this library how can i implement `TickerProviderStateMixin` or `SingleTickerProviderStateMixin` the same as `StatefulWidget`? i know i can separate part of code as a simple class but i want to use in main class

**Comment by MbIXjkee** [comment]
Hi. There are some ready-to-use mixins for ticker provider. https://github.com/Elementary-team/flutter-elementary/blob/main/packages/elementary/lib/src/ticker/ticker_providers.dart
They are should be applied to WidgetModel.

**Comment by pishguy** [comment]
@MbIXjkee could you tell me how can i implement `createTicker` method? 

for example this is my simple `viewModel` class:

```dart
LocationScreenWidgetModel defaultLocationScreenWidgetModelFactory(BuildContext context) {
  final model = context.read<LocationScreenModel>();
  return LocationScreenWidgetModel(model,);
}

class LocationScreenWidgetModel extends WidgetModel<LocationScreenWidget, LocationScreenModel> implements ILocationScreenWidgetModel, SingleTickerProviderWidgetModelMixin {
  LocationScreenWidgetModel(super.model);

 ///

  @override
  Ticker createTicker(TickerCallback onTick) {
    // TODO: implement createTicker
    throw UnimplementedError();
  }
}

abstract class ILocationScreenWidgetModel implements IWidgetModel {
///
}
```

thanks

**Comment by MbIXjkee** [comment]
You don't need to implement createTicker, there is packages/elementary/lib/src/ticker/ticker_providers.dart with mixins that are already implemented everything needs to be a tickerProvider. When you need AnimationController, you just create it inside WM (with mixin) and provide `this` inside as a ticker provider.
