### ISSUE TITLE
when initWidgetModel() initializing?

### ISSUE THREAD

**Issue by pishguy** [Elementary-team/flutter-elementary#89]
in this code i pasted my simplified `MVVM` which in that i defined `width`, but in widget i get 

```
LateInitializationError: Field '_width@234398598' has not been initialized.
```

error and i'm not sure how can i resolve that

```dart
class ManageAddressesWidgetModel extends ...{

  late double _width;

  @override
  double get width => _width;

  @override
  void initWidgetModel() {
    super.initWidgetModel();
    Future.microtask(() => _width = context.size!.width);
  }
}

abstract interface class IManageAddressesWidgetModel implements IWidgetModel {
  double get width;
}

```

**Comment by MbIXjkee** [comment]
Hi, you use there a microtask, which is run asynchronously later. So when you use this property in a widget, it is not initialized yet. You can do the same without microtask, initWidgetModel is called when the element related to this WidgetModel is already in the element tree.
And generally, not relative to Elementary, it is not good for an application performance to use microtask for something like this.

**Comment by pishguy** [comment]
@MbIXjkee without `microtask` i get `LateInitializationError` error, did you tested that?
